### ISSUE TITLE
Random session

### ISSUE THREAD

**Issue by dovidkopel** [benas/random-beans#187] opened 2016-08-15 13:22 UTC
Support a notion of a random session. There we may be able to track many objects and continue to support them in their object lifecycle. Think along the lines of a complex database architecture. Such that you have many objects that relate to each other. You will want to create many objects and verify that the other ones already exist. This is related to https://github.com/benas/random-beans/issues/186 and https://github.com/benas/random-beans/issues/185. The reality is this mostly tracking object metadata and random constraints. This would likely tie in with an in-memory database and an ORM. There is value to this on its own just by saying this is one session. A possible concept may be within a session generate up to _n_ instances of this class, after that use cached. Perhaps keep creating this class instance but ensure that this field is unique with respect to already generated values.

**Comment by benas** [comment] 2016-08-23 21:37
> A possible concept may be within a session generate up to n instances of this class, after that use cached

This is already implemented but not visible. For case like:

```java
class Person {
   private String name;
   private Person parent;
}
```

As described in #44 , this will cause an infinite recursion. We have fixed the problem with a pool of object for all known types. The problem is that the pool size is fixed to 10 and is not configurable. So in this case, RB will generate 10 distinct random instances of `Person`, after that, it will use cached instances.

> A possible concept may be within a session generate up to n instances of this class, after that use cached.

n is currently = 10. This should be configurable at construction time just like other parameters. What do you think?

**Comment by benas** [comment] 2016-09-23 18:59
> A possible concept may be within a session generate up to n instances of this class, after that use cached.

As discussed in my previous comment, this is a duplicate of #182 . I'm closing this issue

**Closed by benas** 2016-09-23 18:59 UTC
