### ISSUE TITLE
[feature request] add method Rnadomizer.getBeanInstance() so that can create fields with relations.

### ISSUE THREAD

**Issue by jiming** [benas/random-beans#302] opened 2018-04-25 09:54 UTC
```
interface Randomizer<T, CREATED_BEAN> {
        default CREATED_BEAN getBeanInstance() {return null;}

        /**
         * Generate a random value for the given type.
         *
         * @return a random value for the given type
         */
        T getRandomValue();
    }

    class Job {
        long startTime;
        long endTime;
    }

    class JobEndTimeRandomizer implements Randomizer<Long, Job> {

        @Override
        public Long getRandomValue() {
            return getBeanInstance().startTime + random.nextInt();
        }
    }

```

**Comment by benas** [comment] 2018-11-24 20:30
Hi,

This is a duplicate of https://github.com/benas/random-beans/issues/6. The idea is the same, getting access to the currently randomized object so that we can customize the logic.

I think this is better implemented by adding the current bean instance to the `RandomizationContext` (need to be made public) and create a new interface `ContextAwareRandomizer` (extends `Randomizer`) that makes the randomizer aware of the context and hence the current instance (the context can contain other useful information as well).

I'm closing this issue as duplicate.

Kr,
Mahmoud

**Closed by benas** 2018-11-24 20:30 UTC
