### ISSUE TITLE
More flexibility with regards to recursion 

### ISSUE THREAD

**Issue by dovidkopel** [benas/random-beans#186] opened 2016-08-15 13:17 UTC
I will go in more depth shortly but I just want to note that we need a way to provide more control regarding repeated and recursion of entities. On a simple level provide a default recursion handle that would see a field in the stack and say if this field has been generated once don't generate it again. Allow for that to be configured to a max number, or a range (if by random). Also provide the capacity to have a predicate to determine at runtime when looking at the field and stack whether a new object should be created or return the cached object.

This is important because at times you may want to make entities with relationships that should be unique but have the same types. This is related to another issue I created regarding JPA relationship types.

**Comment by JesusMetapack** [comment] 2016-08-19 13:33
I found beans with this issue.. For example if a bean of type A contains a property of type B, and a bean of type B contains a property of type A, it creates a very big sequence of objects, and Jackson fails to serialize

**Comment by benas** [comment] 2016-08-23 21:39
This is already implemented but not visible. For case like:

```java
class Person {
   private String name;
   private Person parent;
}
```

As described in #44 , this will cause an infinite recursion. We have fixed the problem with a pool of object for all known types. The problem is that the pool size is fixed to 10 and is not configurable. So in this case, RB will generate 10 distinct random instances of `Person`, after that, it will use cached instances. The pool size should be configurable at construction time just like other parameters. What do you think?

**Comment by MarvinWyrich** [comment] 2016-09-15 16:27
> The pool size should be configurable at construction time just like other parameters. What do you think?

Yes, this is [very desirable](https://github.com/benas/random-beans/issues/182) ;)

**Comment by benas** [comment] 2016-09-23 18:56
@dovidkopel @JesusMetapack 

We have added a parameter to control the object pool size (see #182 ) . I think this new parameter is what you are looking for. If it's the case, please let me know in order to close this issue.

**Closed** 2016-10-01 20:40 UTC
Labels: waiting-for-feedback
