### ISSUE TITLE
Enhance field definition to specify a path similar to the Commons PropertyUtils 

### ISSUE THREAD

**Issue by JesusMetapack** [benas/random-beans#188] opened 2016-08-19 13:31 UTC
When trying to exclude fields from being generated randomly, I found that its not possible to specify very specific fields to be excluded.
The only way to specify a field, its by name and type

but lets say I have a bean with a property getA().getB().getC() of type Integer
The only way to exclude the C property in that bean is to provide a fieldDefinition with name = "c"  and type = Integer.
If there was another integer property getA().getC() in the same bean, then it also gets excluded.

I think the fieldDefinition should be able to specify the path to a particular property
so in the first case the path would be = "a.b.c"  , rather than just name and type

**Comment by benas** [comment] 2016-08-19 13:37
Hi,

You can already exclude fields using the dotted notation. Here is an example:

https://github.com/benas/random-beans/blob/master/random-beans/src/test/java/io/github/benas/randombeans/FieldExclusionTest.java#L109

Is this what you are looking for?

Kind regards
Mahmoud

**Comment by JesusMetapack** [comment] 2016-08-19 14:24
Nice one. Sorry but I couldn't see an example

**Comment by JesusMetapack** [comment] 2016-08-19 14:31
Does that also work excluding by FieldDefinition when you use EnhancedRandomBuilder? Just to be consistent

**Comment by benas** [comment] 2016-08-19 14:51
> The only way to specify a field, its by name and type

Hmm, you can also specify the declaring type of the field (`inClass` method) and probably present annotations (`isAnnotatedWith` method)

> but lets say I have a bean with a property getA().getB().getC() of type Integer
The only way to exclude the C property in that bean is to provide a fieldDefinition with name = "c" and type = Integer.


You can be more specific by providing the declaring class and there would be no confusion. In your example, you can write:

```
EnhancedRandom enhancedRandom = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
   .exclude(FieldDefinitionBuilder.field().named("c").ofType(Integer.class).inClass(TypeOfB.class).get())
   .build();
```

> If there was another integer property getA().getC() in the same bean, then it also gets excluded.

With the previous snippet, " getA().getC() in the same bean" would not be excluded

> Does that also work excluding by FieldDefinition when you use EnhancedRandomBuilder? Just to be consistent

No, dotted notation is not possible with FieldDefinition. But this feature should be added to the library. here is an example:

```
EnhancedRandom enhancedRandom = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
   .exclude(FieldDefinitionBuilder.field().named("a.b.c").ofType(Integer.class).inClass(MyBean.class).get())
   .build();

Person person = enhancedRandom.nextObject(Person.class);
```

This would exclude field "a.b.c" *starting* from type `MyBean` and not `Person`

**Comment by benas** [comment] 2016-11-09 12:09
Work in progress (branch issue-188)

**Comment by benas** [comment] 2016-11-09 15:43
Hi @JesusMetapack 

I was working on implementing this feature but looking at some examples, I'm finally not sure if it should be added. Here is the example:

```
@Test
public void excludedDottedFieldsWithFieldDefinitionShouldNotBePopulated() {
    // given
    enhancedRandom = aNewEnhancedRandomBuilder()
            .exclude(field().named("street.name").ofType(String.class).inClass(Address.class).get())
            .build();

    // when
    Person person = enhancedRandom.nextObject(Person.class);

    // then
    assertThat(person).isNotNull();
    assertThat(person.getAddress()).isNotNull();
    assertThat(person.getAddress().getStreet()).isNotNull();
    assertThat(person.getAddress().getStreet().getName()).isNull();
}
```

In this example, the Person type has an Address, which has a Street, which has a name (and other fields). 

The way I am excluding the `name` field from the `Street` object:

```
.exclude(field().named("street.name").ofType(String.class).inClass(Address.class).get())
```

Could be written like this:

```
.exclude(field().named("name").ofType(String.class).inClass(Street.class).get())
```

This is possible because it's easy to express fine-grained exclusions with FieldDefinition (and can chain many exclusions using the builder), which is not the case using the `nextObject()` method.

What I mean is that the dotted notation has an added value when used in `nextObject()` or `objects()` methods, but not when used with FieldDefinition since we can precisely tell what field to exclude  and chain many exclusions. Do you agree?

> Does that also work excluding by FieldDefinition when you use EnhancedRandomBuilder? Just to be consistent

So the question now is probably: "**should** it also work with FieldDefinition ? I'm not sure since we can precisely describe which field should be excluded. That said, do you think if dotted notation is not supported in FieldDefinition that would be inconsistent?

Kind regards
Mahmoud

**Comment by JesusMetapack** [comment] 2016-11-09 16:37
Well.. The dotted notation still makes possible some other use cases
For example in our case we had this kind of recursive hierarchy

C
   B b
   C c
       B b

If you wanted to override  the “b" property differently depending where it is in the herarchy, it wouldn’t be possible to do it with just the FieldDefintion(“b”).ofType(B).InClass(C)., because all the b properties will be considered the same
Anyway, we are happy wit the version that we were using last, and we use the dotted notation that you provided

Thanks

**Comment by benas** [comment] 2016-11-10 09:05
> If you wanted to override  the “b" property differently depending where it is in the hierarchy, it wouldn’t be possible to do it with just the FieldDefintion(“b”).ofType(B).InClass(C)., because all the b properties will be considered the same

Exact, "depending where it is in the hierarchy" is the population context.
It is impossible to do it with FieldDefinition because FieldDefinition is independent from any context.. and that's why I'm struggling to find a clean way to implement dotted notation with FieldDefinition.. Probably it's just impossible "by design" with the current design :smile: 

To do it properly, we need to have access to the population context in addition to the field being populated [here](https://github.com/benas/random-beans/blob/master/random-beans/src/main/java/io/github/benas/randombeans/randomizers/registry/ExclusionRandomizerRegistry.java#L62). But this requires major API changes (make `PopulationContext` public and add it as a parameter in `RandomizerRegistry#getRandomizer(Field field)`).

> Anyway, we are happy wit the version that we were using last, and we use the dotted notation that you provided

Ok that's fine for now, but I'll plan the requested feature for the next major release (4.x).

Kind regards

**Comment by JesusMetapack** [comment] 2016-11-10 09:07
Thanks

**Comment by benas** [comment] 2019-02-17 17:32
Hi @JesusMetapack 

> For example in our case we had this kind of recursive hierarchy

```
C
   B b
   C c
       B b
```

> If you wanted to override the “b" property differently depending where it is in the herarchy, it wouldn’t be possible to do it with just the FieldDefintion(“b”).ofType(B).InClass(C)., because all the b properties will be considered the same

I evaluated the breaking change needed to implement this feature and it is not worth the case we are trying to cover. FTR, we are introducing a new API called `ContextAwareRandomizer` (see issue #6) that allows a randomizer to be aware of the randomization context (root object being randomized, current object in the graph, parameters, etc). In your case, it will be possible to use a custom context aware randomizer and by having access to the root object (`C`) and the currently randomized object (either the first `B` or the second one), you can have full control on the randomization of `B` "depending on where it is in the hierarchy" (either return a random value or null to exclude it). Does this make sense?

> Anyway, we are happy wit the version that we were using last, and we use the dotted notation that you provided

Cool. In that case, I think we can close this issue. Do you agree?

**Comment by benas** [comment] 2019-02-23 23:34
Hi @JesusMetapack ,

> In your case, it will be possible to use a custom context aware randomizer and by having access to the root object (`C`) and the currently randomized object (either the first `B` or the second one), you can have full control on the randomization of `B` "depending on where it is in the hierarchy" (either return a random value or null to exclude it). Does this make sense?

I wanted to give an example for this use case using a `ContextAwareRandomizer`. Let's say we have the following type:

```java
class Person {
        private String name;
        private Person bestFriend;
}
```

This is the same as your example where `C = Person`, `B = String`, `b = name` and `c = bestFriend`. It is just a more realistic object graph.

> If you wanted to override the “b" property differently depending where it is in the herarchy, it wouldn’t be possible to do it with just the FieldDefintion(“b”).ofType(B).InClass(C)., because all the b properties will be considered the same

This means that you want to generate the person name depending on where you are in the hierarchy. For example, let' say we want to generate the person name as `foo` and the name of its best friend as `bar`. The following field definition will match the person's name **as well as** the person's best friend name:

```java
FieldDefinitionBuilder.field().named("name").ofType(String.class).inClass(Person.class).get()
```

Now here is the most important point in the story: In order to determine "where we are in the hierarchy" and generate the name accordingly, aka if we are at the person level or at the best friend level, we can use a context aware randomizer like:

```java
class NameRandomizer implements ContextAwareRandomizer<String> {

        private RandomizerContext context;

        @Override
        public void setRandomizerContext(RandomizerContext context) {
            this.context = context;
        }

        @Override
        public String getRandomValue() {
            if (context.getCurrentField().equals("bestFriend.name")) { // or context.getRandomizationDepth() == 2
                return "bar";
            }
            return "foo";
        }
    }
```

The randomization context (coming in v3.9 through issue #6) allows you to get access to the current randomization depth as well as the full path to the current field name with dotted notation (and other details too). With all these details, you have full control on how to randomize the field.

Here is a test case passing with v3.9.0-SNAPSHOT:

```java
import io.github.benas.randombeans.api.ContextAwareRandomizer;
import io.github.benas.randombeans.api.EnhancedRandom;
import io.github.benas.randombeans.api.RandomizerContext;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class Issue188 {

    @Test
    void testRandomizerContext() {
        // given
        EnhancedRandom enhancedRandom = new EnhancedRandomBuilder()
                .randomize(FieldDefinitionBuilder.field().named("name").ofType(String.class).inClass(Person.class).get(), new NameRandomizer())
                .build();

        // when
        Person person = enhancedRandom.nextObject(Person.class);

        // then
        assertThat(person).isNotNull();
        assertThat(person.getName()).isEqualTo("foo");
        assertThat(person.getBestFriend()).isNotNull();
        assertThat(person.getBestFriend().getName()).isEqualTo("bar");
        assertThat(person.getBestFriend().getBestFriend()).isNotNull();
    }

    static class NameRandomizer implements ContextAwareRandomizer<String> {

        private RandomizerContext context;

        @Override
        public void setRandomizerContext(RandomizerContext context) {
            this.context = context;
        }

        @Override
        public String getRandomValue() {
            if (context.getCurrentField().equals("bestFriend.name")) { // or context.getRandomizationDepth() == 2
                return "bar";
            }
            return "foo";
        }
    }

    static class Person {
        private String name;
        private Person bestFriend;

        public Person() { }
        public String getName() { return name; }
        public void setName(String name) { this.name = name; }
        public Person getBestFriend() { return bestFriend; }
        public void setBestFriend(Person bestFriend) { this.bestFriend = bestFriend; }
    }
}
```

I hope this example makes the usage of the randomization context a bit clearer to understand how to cover the use case you presented.

With that said, I'm closing this issue, but you can add comments if you want.

Best regards,
Mahmoud

**Closed by benas** 2019-02-23 23:34 UTC
Labels: enhancement, feature, in-progress, requires-major-API-change, waiting-for-feedback
