### ISSUE TITLE
equal objects in loop

### ISSUE THREAD

**Issue by alimohebbi** [benas/random-beans#193] opened 2016-08-31 08:22 UTC
if you use random.nextObject in a loop after a while it creates equal object. for example after 1000 time.

**Comment by PascalSchumacher** [comment] 2016-08-31 19:25
That is by design. See http://www.gitterforum.com/discussion/benas-random-beans?page=7  for more information. I'm closing this issue because it duplicates https://github.com/benas/random-beans/issues/182.

**Closed by PascalSchumacher** 2016-08-31 19:25 UTC
