### ISSUE TITLE
java.lang.InstantiationError: com.fasterxml.jackson.core.ObjectCodec

### ISSUE THREAD

**Issue by maassql** [benas/random-beans#150] opened 2016-06-16 19:09 UTC
I was very excited to find this project.  Unfortunately, I have run out of time researching this error.  Below is as much information as I can figure you might need.  I am only submitting this so that I might learn something.  I am going to move back to tedious boilerplate code now.  I will set a tag in my codebase in case you want me to provide more information.  Of course, if this is a big 'well duh' for you, I would welcome the learning experience ;).

#### Console output
```
Caused by: io.github.benas.randombeans.api.ObjectGenerationException: Unable to generate a random instance of type class {my custom class}
	at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:126)
	at io.github.benas.randombeans.FieldPopulator.generateRandomValue(FieldPopulator.java:106)
	at io.github.benas.randombeans.FieldPopulator.populateField(FieldPopulator.java:80)
	at io.github.benas.randombeans.EnhancedRandomImpl.populateField(EnhancedRandomImpl.java:154)
	at io.github.benas.randombeans.EnhancedRandomImpl.populateFields(EnhancedRandomImpl.java:148)
	at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:122)
	... 62 more
Caused by: io.github.benas.randombeans.api.ObjectGenerationException: Unable to generate a random instance of type class com.fasterxml.jackson.databind.ObjectMapper
	at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:126)
	at io.github.benas.randombeans.FieldPopulator.generateRandomValue(FieldPopulator.java:106)
	at io.github.benas.randombeans.FieldPopulator.populateField(FieldPopulator.java:80)
	at io.github.benas.randombeans.EnhancedRandomImpl.populateField(EnhancedRandomImpl.java:154)
	at io.github.benas.randombeans.EnhancedRandomImpl.populateFields(EnhancedRandomImpl.java:148)
	at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:122)
	... 67 more
Caused by: io.github.benas.randombeans.api.ObjectGenerationException: Unable to generate a random instance of type class com.fasterxml.jackson.core.JsonFactory
	at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:126)
	at io.github.benas.randombeans.FieldPopulator.generateRandomValue(FieldPopulator.java:106)
	at io.github.benas.randombeans.FieldPopulator.populateField(FieldPopulator.java:80)
	at io.github.benas.randombeans.EnhancedRandomImpl.populateField(EnhancedRandomImpl.java:154)
	at io.github.benas.randombeans.EnhancedRandomImpl.populateFields(EnhancedRandomImpl.java:148)
	at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:122)
	... 72 more
Caused by: io.github.benas.randombeans.api.ObjectGenerationException: Unable to generate a random instance of type class com.fasterxml.jackson.core.ObjectCodec
	at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:126)
	at io.github.benas.randombeans.FieldPopulator.generateRandomValue(FieldPopulator.java:106)
	at io.github.benas.randombeans.FieldPopulator.populateField(FieldPopulator.java:80)
	at io.github.benas.randombeans.EnhancedRandomImpl.populateField(EnhancedRandomImpl.java:154)
	at io.github.benas.randombeans.EnhancedRandomImpl.populateFields(EnhancedRandomImpl.java:148)
	at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:122)
	... 77 more
Caused by: java.lang.InstantiationError: com.fasterxml.jackson.core.ObjectCodec
	at sun.reflect.GeneratedSerializationConstructorAccessor12.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:45)
	at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
	at io.github.benas.randombeans.ObjectFactory.createNewInstance(ObjectFactory.java:69)
	at io.github.benas.randombeans.ObjectFactory.createInstance(ObjectFactory.java:61)
	at io.github.benas.randombeans.EnhancedRandomImpl.doPopulateBean(EnhancedRandomImpl.java:112)
	... 82 more
```
#### POM
```
		<dependency>
		    <groupId>io.github.benas</groupId>
		    <artifactId>random-beans</artifactId>
		    <version>3.0.0</version>
		</dependency>
		<dependency>
		   <groupId>io.github.benas</groupId>
		   <artifactId>random-beans-jodatime</artifactId>
		   <version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.7.4</version>
		</dependency>
```
#### Location
```

import com.fasterxml.jackson.annotation.JsonCreator;

import {my_company's_path}.A_ParamStruct;

public class Location 
	extends 	A_ParamStruct
{
	private static final long serialVersionUID = 5713143987689681018L;
	
	@JsonCreator
	public Location ( float latitude, float longitude ) { this.latitude = latitude; this.longitude = longitude; }
	public float	latitude;
	public float	longitude;
}
```
#### A_ParamStruct
```

import java.io.Serializable;

@SuppressWarnings("serial")
public abstract class A_ParamStruct 
	extends A_SerializesToJson
	implements 
			  I_ParamStruct
			, Cloneable
			, Serializable 
{

}

```

#### A_SerializesToJson
```
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public abstract class A_SerializesToJson 
{
	
	private final static org.apache.logging.log4j.Logger logger = org.apache.logging.log4j.LogManager.getLogger();
	
	protected ObjectMapper jacksonMapper = _s_get_Jackson_ObjectMapper();
	
	private static ObjectMapper _s_get_Jackson_ObjectMapper()
	{
		ObjectMapper ret = new ObjectMapper();
		// http://stackoverflow.com/questions/11757487/how-to-tell-jackson-to-ignore-a-field-during-serialization-if-its-value-is-null
		ret.setSerializationInclusion(Include.NON_NULL);
		return ret;
	}
	
	
	public String asJsonString()
	{
		String ret = null;
		try 
		{
			// Convert object to JSON string and pretty print
			ret = this.jacksonMapper.writerWithDefaultPrettyPrinter().writeValueAsString(this);
		} 
		catch (JsonProcessingException e) 
		{
			logger.error("asJsonString()  |  error converting object to json.", e);
		}
		return ret;
	}
	public String 			toString() 													{ return this.asJsonString(); }

}
```
#### I_ParamStruct 
```
import {my company's path}.I_ResponseContent;


public interface I_ParamStruct 
	extends I_ResponseContent
{
	
}

```

#### I_ResponseContent  
```
public interface I_ResponseContent 
{
	String asJsonString();
}

```

**Comment by PascalSchumacher** [comment] 2016-06-16 20:10
`ObjectCodec` is an abstract class, so it can not be instantiated.

Can you try activating the classpath scanning feature of RandomBeans e.g.:

`EnhancedRandomBuilder.aNewEnhancedRandomBuilder().scanClasspathForConcreteTypes(true).build().random(YourClass.class);`

Maybe that helps.

**Comment by PascalSchumacher** [comment] 2016-06-16 20:42
Classpath scanning won't help, as `ObjectCodec` subclasses can not be created by random beans.

Try excluding `ObjectCodec` from randomization e.g.:

`EnhancedRandomBuilder.aNewEnhancedRandomBuilder().randomize(ObjectCodec.class, new SkipRandomizer()).build().nextObject(YourClass.class);`

**Comment by benas** [comment] 2016-06-17 06:12
Hi @maassql 

Thank you for pointing out this issue.

Which class are you trying to randomize?

**Comment by PascalSchumacher** [comment] 2016-06-17 18:37
I was able to create a `Location` object with `EnhancedRandomBuilder.aNewEnhancedRandomBuilder().randomize(ObjectCodec.class, new SkipRandomizer()).randomize(ObjectCodec.class, new SkipRandomizer()).build().nextObject(Location.class);`, but I fear the resulting is not very useful.

**Comment by PascalSchumacher** [comment] 2016-06-30 18:35
@benas I guess this can be closed due to lack of feedback.

**Comment by benas** [comment] 2016-07-04 09:59
@PascalSchumacher Let me give another chance :smile: 

@maassql I was able to reproduce the "issue", I'm not sure this is really an issue.

The only concrete class in your hierarchy is `Location`, so I tried to randomize one instance of it.
Here are all fields in this class:

* `private static final long serialVersionUID` : static final fields are ignored by random beans, so this field will be ignored
* `public float latitude`: this field can be randomized
* public float longitude`: this field can be randomized
* `protected ObjectMapper jacksonMapper`: it makes no sense to try to randomize this field, so it can be excluded

With the following snippet, I was able to create a random instance of `Location`:

```java
EnhancedRandom enhancedRandom = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
                .build();

        Location location = enhancedRandom.nextObject(Location.class, "jacksonMapper");
        System.out.println(location.latitude);
        System.out.println(location.longitude);
```

You can also exclude fields with a `SkipRandomizer` as described previously by @PascalSchumacher.
There are other ways to exclude fields, they are described [here](https://github.com/benas/random-beans/wiki/excluding-fields).

Could you please give it a try and keep us informed?

Finally with the upcoming release v3.2, you will be able to exclude fields having a given type, like in this case, all fields of type `ObjectMapper`:

```java
EnhancedRandom enhancedRandom = EnhancedRandomBuilder.aNewEnhancedRandomBuilder()
    .exclude(ObjectMapper.class)
    .build();

Location location = enhancedRandom.nextObject(Location.class);
```

Hope this helps.

Kind regards
Mahmoud

**Comment by benas** [comment] 2016-07-05 11:13
@maassql As discussed, the solution is to exclude the `jacksonMapper` field.

I'm closing this issue for next release, feel free to reopen it if you have any question.

Kind regards
Mahmoud

**Closed by benas** 2016-07-05 11:13 UTC
Labels: question
